# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:11.2.0

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

build:
  only:
    - tags
  script:
    - yarn install
    - yarn run init
    - yarn run build
  artifacts:
    name: "CI_PROJECT_NAME-$CI_COMMIT_TAG"
    paths:
      - dist/